version: "3.9"

services:
  open-webui-proxy:
    build: .
    container_name: open-webui-proxy
    restart: always
    environment:
      PROXY_IP: "" 
      PROXY_PORT: ""
      PROXY_USER: ""
      PROXY_PASS: ""
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data

volumes:
  open-webui:

